# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32673316840d0fbd71596cfde179e7239b74c6fdf7449441e9a9da28e7609ba7363d180396561b74e8591b7a669af6883b6d98ae225e97d51777f4e8ec8e51fa

test:
  secret_key_base: 7d8c00f062cb3249a9e29aec7f19097ae874b3bdea715a5799f61f020385d127bec28dabab3a27f885f15c03e927cb966de0db4249efff8218d989ccb852651b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
